name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: ${author}
api-version: 1.19
commands:
  findmystation:
    aliases: [fms]
    description: "Plugin command"
    usage: /findmystation [subcommand]
permissions:
  findmystation.utils.useplugin:
    description: "Allows a player to use the plugins features"
    default: true
  findmystation.utils.animations:
    description: "Allows a player to use rgb station"
    default: false
  findmystation.animations.*:
    description: "Grants access to every animation but only if findmystation.utils.animation is granted too"
    default: false
    children:
      - findmystation.utils.animations
  findmystation.commands.selectanimation:
    description: "Permission to use /findmystation animation select command"
    default: false
  findmystation.commands.listanimation:
    description: "Permission to use /findmystation animation list command"
    default: false
  findmystation.commands.animation:
    description: "Permission to use /findmystation animation command"
    default: false
  findmystation.commands.animation.*:
    description: ""
    default: false
    children:
      - findmystation.commands.animation
      - findmystation.commands.listanimation
      - findmystation.commands.animation
  findmystation.commands.color:
    description: "Permission to use /findmystation color command"
    default: true
  findmystation.commands.reload:
    description: "Permission to use /findmystation reload command"
    default: false
  findmystation.commands.*:
    description: "Permission for all plugin commands"
    children:
      - findmystation.commands.animation
      - findmystation.commands.color
      - findmystation.commands.reload
  findmystation.utils.*:
    description: "Permission for all plugin utils"
    children:
      - findmystation.utils.useplugin
      - findmystation.utils.animations
  findmystation.*:
    description: "Permission for everything"
    children:
      - findmystation.commands.*
      - findmystation.utils.*
      - findmystation.animations.*