name: FindMyStation
version: 1.0
main: de.cuzim1tigaaa.findmystation.FindMyStation
author: CuzIm1Tigaaa
api-version: 1.19
commands:
  findmystation:
    aliases: [fms]
    description: "Plugin command"
    usage: /findmystation [subcommand]